Repository planetarium/sphere, pull requests merged in 2022-10, with the labels that each got.

#12 Add types/node to devDeps of account-local
  packages/account-local/package.json
  yarn.lock
Labels: Extra Small

#16 Improve sign interface
  packages/account-aws-kms/index.ts
  packages/account-raw/index.ts
  packages/sign/index.ts
  packages/sign/package.json
  yarn.lock
Labels: Small

#17 Implement account-aws-kms
  .gitignore
  packages/account-aws-kms/package.json
  packages/account-aws-kms/parseAsn1.ts
  packages/account-aws-kms/tests/tsconfig.json
  packages/account-aws-kms/tsconfig.json
  yarn.lock
Labels: enhancement, Small

#15 Bump bencodex to 0.1.2
  packages/account-raw/tests/address.test.ts
  packages/sign/package.json
  yarn.lock
Labels: Extra Small

#19 Add publishing-related configurations
  package.json
  packages/account-aws-kms/package.json
  packages/account-local/package.json
  packages/account-raw/package.json
  packages/sign/package.json
Labels: Extra Small

#21 Add conditional exports to manage Node.js quirks
  .yarn/patches/nanobundle-npm-0.0.28-6c1dd68c44.patch
  package.json
  packages/sign/package.json
  packages/sign/src/index.ts
  packages/sign/src/util.ts
  packages/sign/src/webcrypto/browser.ts
  packages/sign/src/webcrypto/node.ts
  yarn.lock
Labels: Small

#20 Remove npm protocol in kms dependencies
  packages/account-aws-kms/package.json
  yarn.lock
Labels: Extra Small

#22 Make account-aws-kms always emits lower-s signature
  packages/account-aws-kms/index.ts
  packages/account-aws-kms/package.json
  packages/account-aws-kms/tests/normalize.test.ts
  yarn.lock
Labels: Small

#23 Prioritize CommonJS bundle if required
  packages/sign/package.json
Labels: Extra Small

#24 Add readme and few fixes
  README.md
  packages/account-aws-kms/index.ts
  packages/account-local/index.ts
  packages/account-raw/index.ts
  packages/sign/src/index.ts
Labels: documentation, Small

#25 Return list of uuids in account-local
  packages/account-local/index.ts
  packages/account-local/util.ts
Labels: Extra Small
